<?php /*** @var Products $block */

/**
 *
 * @var Escaper $escaper
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\ActionInterface;
use Magento\Framework\Escaper;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Exception\NoSuchEntityException;
use RLTSquare\WhoBoughtThis\Block\Products;

?>
<?php if ($block->isEnableDisable() == 1): ?>
    <?php try {
    $collection = $block->getCollection();
} catch (LocalizedException $e) {
    echo "we couldn't find any product";
}
    $iterator = 1;
    $image = 'category_page_grid';
    $_helper = $block->getCatalogHelper();
    $listProduct = $block->getListProduct();
    $showCart = true;
    $showCompare = 0;
    $showWishlist = true;
    $showReview = 1;
    $viewMode = 'grid';
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    if (empty($pos)) {
        $pos = 1;
    }

    ?>
    <?php if ($collection && $collection->getData()): ?>
        <div class="products wrapper most_viewed-wrapper custom_grid-wrapper tabproduct-right">
            <div class="block-title-tabs">
                <h3 class="title item"><?= __('Customers Who Bought This Item Also Bought') ?></h3>
            </div>
            <ol class="products list items product-items bought-slider slider">
                <?php foreach ($collection as $data) { ?>
                    <?php try {
        $_product = $block->getLoadProduct($data->getId());
    } catch (NoSuchEntityException $e) {
        echo "We couldn't find loaded products";
    } ?>
                    <?php if ($_product->getID()): ?>
                        <?php /* @escapeNotVerified */ ?>
                        <?php echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info per-product" data-container="product-grid">
                            <?php $productImage = $listProduct->getImage($_product, $image); ?>
                            <?php if ($pos != null): ?>
                                <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                            <?php endif; ?>
                            <div class="images-container">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <div class="product-hover">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php echo $block->getLazyLoadedImage($productImage); ?>
                                    </a>
                                    <?php if ($showWishlist || $showCart): ?>
                                        <div class="hover-box clearfix">
                                            <div
                                                class="product actions clearfix"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                <?php if ($showCart): ?>
                                                    <div
                                                        class="actions-primary actions-cart alotheme-tooltip"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                        <?php if ($_product->isSaleable()): ?>
                                                            <?php $postParams = $listProduct->getAddToCartPostParams($_product); ?>
                                                            <form data-role="tocart-form"
                                                                  action="<?php echo $postParams['action']; ?>"
                                                                  method="post">
                                                                <input type="hidden" name="product"
                                                                       value="<?php echo $postParams['data']['product']; ?>">
                                                                <input type="hidden"
                                                                       name="<?php echo ActionInterface::PARAM_NAME_URL_ENCODED; ?>"
                                                                       value="<?php echo $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED]; ?>">
                                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?php echo $escaper->escapeHtml(__('Add to Cart')); ?>"
                                                                        class="action tocart primary button btn-cart">
                                                                    <span
                                                                        class="tooltip"><?php echo __('Add to Cart') ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <div
                                                                    class="stock available"><span><?php /* @escapeNotVerified */
                                                                        echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div
                                                                    class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                        echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="product details product-item-details products-textlink clearfix">
                                    <h4 class="product-name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>"
                                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                            <?php /* @escapeNotVerified */
                                            try {
                                                echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                                            } catch (LocalizedException $e) {
                                                echo "We Couldn't Find the Products";
                                            } ?>
                                        </a>
                                    </h4>
                                </div>
                            </div>
                        </div>
                        <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                    <?php endif; ?>
                <?php } ?>
            </ol>
        </div>
    <?php endif; ?>
    <?php if (!$listProduct->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }


        </script>
    <?php endif; ?>
    <script>
        // define is used to register a module in require js
        require(['jquery', 'slick'], function ($) {
            //your js code here
            jQuery(function () {
                $(".bought-slider").slick({
                    dots: false,
                    infinite: true,
                    slidesToShow: 6,
                    slidesToScroll: 1,
                    arrows: true,
                    autoplay: false,
                    draggable: true,
                    speed: 300,
                    responsive: [
                        {
                            breakpoint: 1199,
                            settings: {
                                slidesToShow: 4
                            }
                        },
                        {
                            breakpoint: 991,
                            settings: {
                                slidesToShow: 3
                            }
                        },
                        {
                            breakpoint: 639,
                            settings: {
                                slidesToShow: 2
                            }
                        },
                        {
                            breakpoint: 360,
                            settings: {
                                slidesToShow: 2
                            }
                        }
                    ]
                });
                $(".lazy").slick({
                    lazyLoad: 'ondemand', // ondemand progressive anticipated
                    infinite: true
                });
            });
        });
    </script>
<?php endif; ?>
