<?php /** @var Products $block */

/**
 *
 * @var Escaper $escaper
 */
use Magento\Framework\Escaper;
use Magento\Framework\App\ActionInterface;
use RLTSquare\FeaturedProducts\Block\Products; ?>
<?php if ($block->isEnableDisable() && $block->getCurrentPagePath()): ?>
    <?php $collection = $block->getProductCollection();
    $listProduct = $block->getListProduct();
    $iterator = 1;
    $image = 'category_page_grid';
    $pos = $listProduct->getPositioned();
    $_helper = $block->getCatalogHelper();
    $config = $listProduct->getWidgetCfg();
    $showCart = 1;
    $showCompare = 0;
    $showWishlist = 1;
    $showReview = 1;
    $viewMode = 'grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    if(empty($pos)) {$pos = 1;}
    ?>
    <?php if ($collection->getData()): ?>
        <div class="products wrapper most_viewed-wrapper custom_grid-wrapper content-products">
            <?php $iterator = 1; ?>
            <div class="block-title-tabs">
                <h3 class="title item"><?= __('Featured Products') ?></h3>
            </div>
            <ol class="products list items product-items regular slider">
                <?php foreach ($collection->getData() as $data) { ?>
                    <?php $product_id = $data['entity_id']; ?>
                    <?php $_product = $block->getLoadProduct($product_id); ?>
                    <?php if (isset($_product)): ?>
                        <?php if ($_product->getId()): ?>
                            <?php /* @escapeNotVerified */ ?>
                            <?php echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item ">' ?>
                            <div class="product-item-info per-product" data-container="product-grid">
                                <?php $productImage = $listProduct->getImage($_product, $image); ?>
                                <?php if ($pos != null): ?>
                                    <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                                <?php endif; ?>
                                <div class="images-container">
                                    <?php $_productNameStripped = $listProduct->stripTags($_product->getName(), null, true); ?>
                                    <div class="product-hover">
                                        <a href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                           tabindex="-1">
                                            <?php echo $block->getLazyLoadedImage($productImage) ?>
                                        </a>
                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="hover-box clearfix">
                                                <div class="product actions clearfix"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary actions-cart alotheme-tooltip"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                            <?php if ($_product->isSaleable()): ?>
                                                                <?php $postParams = $listProduct->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                      action="<?php echo $postParams['action']; ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?php echo $postParams['data']['product']; ?>">
                                                                    <input type="hidden"
                                                                           name="<?php echo ActionInterface::PARAM_NAME_URL_ENCODED; ?>"
                                                                           value="<?php echo $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED]; ?>">
                                                                    <?php echo $listProduct->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?php echo $escaper->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary button btn-cart">
                                                                <span class="tooltip"><?php echo __('Add to Cart') ?>
                                                                </span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                            echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                            echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="product details product-item-details products-textlink clearfix">
                                        <?php echo $listProduct->getProductPrice($_product) ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div data-role="add-to-links"
                                                 class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       class="action towishlist alotheme-tooltip"
                                                       title="<?php echo $escaper->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $escaper->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $listProduct->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <i class="fa fa-heart icon icons"></i>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <h4 class="product-name product-item-name">
                                            <a class="product-item-link"
                                               href="<?php /* @escapeNotVerified */
                                               echo $_product->getProductUrl() ?>"
                                               title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                <?php /* @escapeNotVerified */
                                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                            </a>
                                        </h4>
                                        <?php echo $showReview ? $listProduct->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php } ?>
            </ol>
        </div>
    <?php endif; ?>

    <script>
        // define is used to register a module in require js
        require(['jquery', 'slick'], function ($) {
            //your js code here
            jQuery(function () {
                if (!$('.regular').hasClass('slick-initialized')) {
                    $(".regular").slick({
                        dots: false,
                        infinite: true,
                        slidesToShow: 6,
                        slidesToScroll: 1,
                        arrows: true,
                        autoplay: false,
                        draggable: true,
                        speed: 300,
                        responsive: [
                            {
                                breakpoint: 1199,
                                settings: {
                                    slidesToShow: 4
                                }
                            },
                            {
                                breakpoint: 991,
                                settings: {
                                    slidesToShow: 3
                                }
                            },
                            {
                                breakpoint: 639,
                                settings: {
                                    slidesToShow: 2
                                }
                            },
                            {
                                breakpoint: 360,
                                settings: {
                                    slidesToShow: 2
                                }
                            }
                        ]
                    });
                    $(".lazy").slick({
                        lazyLoad: 'ondemand', // ondemand progressive anticipated
                        infinite: true
                    });
                }
            });
        });
    </script>
<?php endif; ?>
